### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by robinhouston** [omniscale/imposm3#124]
I got the following crash while running `imposm3 import` using a newly-built imposm3 on the .pbf file downloaded from `http://download.geofabrik.de/north-america-latest.osm.pbf`, which has MD5 sum `04222a0c78bf400681e7000bd713d62a`. I’m running on macOS 10.12.1, and it was built with go 1.6.2.

Any idea what this is about? Is my build broken?

(The amusing address `0xb01dfacedebac1e` is explained [here](https://codereview.appspot.com/83270049).)

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x401045b]

runtime stack:
runtime.throw(0x46f8d40, 0x2a)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x492be80)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).freeSpan.func1()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:726 +0x186
runtime.systemstack(0x70000ed7bb30)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).freeSpan(0x492be80, 0x5212d98, 0x1)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:727 +0x44
runtime.(*mspan).sweep(0x5212d98, 0x5212d00, 0x4053a01)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mgcsweep.go:342 +0x6ef
runtime.(*mheap).reclaimList(0x492be80, 0x492c6e8, 0x5, 0x5747e01)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:347 +0xf3
runtime.(*mheap).reclaim(0x492be80, 0x5)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:374 +0x6b
runtime.(*mheap).alloc_m(0x492be80, 0x5, 0x100000000, 0x70000ed7bdb0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:428 +0x96
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x70000ed7bdc8)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x492be80, 0x5, 0x100000000, 0x4015e0c)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:503 +0x63
runtime.largeAlloc(0xa000, 0x3, 0x41)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/malloc.go:766 +0xb3
runtime.mallocgc.func3()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/malloc.go:664 +0x33
runtime.systemstack(0xc82001a000)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/proc.go:1051

goroutine 29 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:245 fp=0xc820052848 sp=0xc820052840
runtime.mallocgc(0xa000, 0x0, 0x3, 0xc8203ce000)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/malloc.go:665 +0x9eb fp=0xc820052920 sp=0xc820052848
runtime.rawmem(0xa000, 0x1f00)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/malloc.go:809 +0x32 fp=0xc820052948 sp=0xc820052920
runtime.growslice(0x44a8360, 0xc8203ce000, 0x1bc0, 0x1bc0, 0x1bc1, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/slice.go:95 +0x233 fp=0xc8200529b8 sp=0xc820052948
github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto.(*Buffer).dec_slice_packed_int32(0xc820062270, 0xc8203dd8c0, 0xc820134000, 0x0, 0x0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto/decode.go:607 +0x1bf fp=0xc820052a50 sp=0xc8200529b8
github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto.(*Buffer).unmarshalType(0xc820062270, 0x508a0a8, 0x45dea80, 0xc820056ee0, 0x0, 0xc820134000, 0x0, 0x0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto/decode.go:399 +0xd8c fp=0xc820052dc8 sp=0xc820052a50
github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto.(*Buffer).dec_struct_message(0xc820062270, 0xc8203dd7a0, 0xc820408200, 0x0, 0x0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto/decode.go:777 +0x2fe fp=0xc820052e98 sp=0xc820052dc8
github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto.(*Buffer).unmarshalType(0xc820062270, 0x508a0a8, 0x45d4c00, 0xc820056d90, 0x0, 0xc820408200, 0x0, 0x0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto/decode.go:399 +0xd8c fp=0xc820053210 sp=0xc820052e98
github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto.(*Buffer).dec_struct_message(0xc820062270, 0xc8203dd560, 0xc820408180, 0x0, 0x0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto/decode.go:777 +0x2fe fp=0xc8200532e0 sp=0xc820053210
github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto.(*Buffer).unmarshalType(0xc820062270, 0x508a0a8, 0x45d4d80, 0xc820056540, 0x27800, 0xc820408180, 0x0, 0x0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto/decode.go:399 +0xd8c fp=0xc820053658 sp=0xc8200532e0
github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto.(*Buffer).dec_slice_struct(0xc820062270, 0xc8203dc360, 0x27e00, 0xc8200aa180, 0x0, 0x0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto/decode.go:821 +0x3b3 fp=0xc820053748 sp=0xc820053658
github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto.(*Buffer).dec_slice_struct_message(0xc820062270, 0xc8203dc360, 0xc8200aa180, 0x0, 0x0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto/decode.go:786 +0x46 fp=0xc820053780 sp=0xc820053748
github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto.(*Buffer).unmarshalType(0xc820062270, 0x508a0a8, 0x45def60, 0xc8200562a0, 0xc8200aa100, 0xc8200aa180, 0x0, 0x0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto/decode.go:399 +0xd8c fp=0xc820053af8 sp=0xc820053780
github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto.(*Buffer).Unmarshal(0xc820062270, 0x508a550, 0xc8200aa180, 0x0, 0x0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto/decode.go:334 +0x247 fp=0xc820053bc0 sp=0xc820053af8
github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto.UnmarshalMerge(0xc820bae000, 0x27e7b, 0x27e7b, 0x508a550, 0xc8200aa180, 0x0, 0x0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto/decode.go:314 +0x15c fp=0xc820053c38 sp=0xc820053bc0
github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto.Unmarshal(0xc820bae000, 0x27e7b, 0x27e7b, 0x508a550, 0xc8200aa180, 0x0, 0x0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/vendor/github.com/golang/protobuf/proto/decode.go:300 +0x69 fp=0xc820053c78 sp=0xc820053c38
github.com/omniscale/imposm3/parser/pbf.readPrimitiveBlock(0x7fff5fbfe318, 0x20, 0x5cf00f9, 0x16da9, 0xa1)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:79 +0x1e7 fp=0xc820053d78 sp=0xc820053c78
github.com/omniscale/imposm3/parser/pbf.(*parser).parseBlock(0xc8200b2af0, 0x7fff5fbfe318, 0x20, 0x5cf00f9, 0x16da9)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/process.go:86 +0x58 fp=0xc820053f18 sp=0xc820053d78
github.com/omniscale/imposm3/parser/pbf.(*parser).Parse.func1(0xc8201aec60, 0xc8200b2af0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/process.go:40 +0xb0 fp=0xc820053f90 sp=0xc820053f18
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820053f98 sp=0xc820053f90
created by github.com/omniscale/imposm3/parser/pbf.(*parser).Parse
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/process.go:49 +0x95

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc8200b2b2c)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc8200b2b20)
	/usr/local/Cellar/go/1.6.2/libexec/src/sync/waitgroup.go:127 +0xb4
github.com/omniscale/imposm3/parser/pbf.(*parser).Parse(0xc8200b2af0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/process.go:51 +0xc9
github.com/omniscale/imposm3/reader.ReadPbf(0xc8201acf80, 0xc8201c2100, 0xc8200b04c0, 0xc8201aadb0, 0x0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/reader/reader.go:241 +0x948
github.com/omniscale/imposm3/import_.Import()
	/Users/robin/src/go/src/github.com/omniscale/imposm3/import_/import.go:120 +0xa88
github.com/omniscale/imposm3/cmd.Main(0x47458c0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/cmd/main.go:46 +0x2d8
main.main()
	/Users/robin/src/go/src/github.com/omniscale/imposm3/imposm3.go:8 +0x23

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [select]:
github.com/omniscale/imposm3/logging.(*LogBroker).loop(0x4926a40)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/logging/logger.go:143 +0x870
created by github.com/omniscale/imposm3/logging.init.1
	/Users/robin/src/go/src/github.com/omniscale/imposm3/logging/logger.go:240 +0x171

goroutine 19 [chan receive]:
database/sql.(*DB).connectionOpener(0xc820155130)
	/usr/local/Cellar/go/1.6.2/libexec/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/Cellar/go/1.6.2/libexec/src/database/sql/sql.go:493 +0x33f

goroutine 20 [select]:
github.com/omniscale/imposm3/stats.(*Statistics).loop(0xc8201c2100)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/stats/stats.go:109 +0x1be
created by github.com/omniscale/imposm3/stats.NewStatsReporter
	/Users/robin/src/go/src/github.com/omniscale/imposm3/stats/stats.go:88 +0xa6

goroutine 21 [chan receive]:
github.com/omniscale/imposm3/reader.ReadPbf.func3(0xc8200b04c0, 0xc8201aea80, 0xc8201c2310, 0xc8201c2288, 0xc8201acf80, 0xc8201c2100, 0xc8201c2320)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/reader/reader.go:105 +0xc2
created by github.com/omniscale/imposm3/reader.ReadPbf
	/Users/robin/src/go/src/github.com/omniscale/imposm3/reader/reader.go:138 +0x6a3

goroutine 22 [chan receive]:
github.com/omniscale/imposm3/reader.ReadPbf.func4(0xc8200b04c0, 0xc8201aeb40, 0xc8201c2288, 0xc8201acf80, 0xc8201c2100, 0xc8201c2320)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/reader/reader.go:147 +0xc2
created by github.com/omniscale/imposm3/reader.ReadPbf
	/Users/robin/src/go/src/github.com/omniscale/imposm3/reader/reader.go:176 +0x757

goroutine 23 [runnable, locked to thread]:
github.com/omniscale/imposm3/vendor/github.com/jmhodges/levigo._Cfunc_leveldb_put(0x5400e20, 0x5400340, 0xc8201bf0e0, 0x8, 0xc820db6800, 0x116, 0xc8202a2060)
	github.com/omniscale/imposm3/vendor/github.com/jmhodges/levigo/_obj/_cgo_gotypes.go:715 +0x3a
github.com/omniscale/imposm3/vendor/github.com/jmhodges/levigo.(*DB).Put(0xc8200ae430, 0xc8200ae438, 0xc8201bf0e0, 0x8, 0x8, 0xc820db6800, 0x116, 0x200, 0x0, 0x0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/vendor/github.com/jmhodges/levigo/db.go:146 +0x30c
github.com/omniscale/imposm3/cache.(*DeltaCoordsCache).putCoordsPacked(0xc8201ae6c0, 0x182840, 0xc8209b9980, 0x20, 0x1574, 0x0, 0x0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/cache/delta.go:284 +0x302
github.com/omniscale/imposm3/cache.(*DeltaCoordsCache).PutCoords(0xc8201ae6c0, 0xc8209a6000, 0x1f40, 0x1f40, 0x0, 0x0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/cache/delta.go:231 +0x260
github.com/omniscale/imposm3/reader.ReadPbf.func5(0xc8201ae9c0, 0xc8201c2300, 0xc8201c2288, 0x0, 0xc8201acf80, 0xc8201c2100, 0xc8201c2320)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/reader/reader.go:202 +0x226
created by github.com/omniscale/imposm3/reader.ReadPbf
	/Users/robin/src/go/src/github.com/omniscale/imposm3/reader/reader.go:206 +0x832

goroutine 24 [chan receive]:
github.com/omniscale/imposm3/reader.ReadPbf.func6(0xc8200b04c0, 0xc8201ae900, 0xc8201c2300, 0xc8201c2288, 0x0, 0xc8201acf80, 0xc8201c2100, 0xc8201c2320)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/reader/reader.go:216 +0xc6
created by github.com/omniscale/imposm3/reader.ReadPbf
	/Users/robin/src/go/src/github.com/omniscale/imposm3/reader/reader.go:238 +0x91a

goroutine 25 [chan send]:
github.com/omniscale/imposm3/parser/pbf.(*Pbf).BlockPositions.func1(0xc8201aadb0, 0xc8200ae510)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:180 +0x191
created by github.com/omniscale/imposm3/parser/pbf.(*Pbf).BlockPositions
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:182 +0x96

goroutine 26 [chan send]:
github.com/omniscale/imposm3/parser/pbf.(*parser).parseBlock(0xc8200b2af0, 0x7fff5fbfe318, 0x20, 0x5cc1a90, 0x17be9)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/process.go:95 +0x53d
github.com/omniscale/imposm3/parser/pbf.(*parser).Parse.func1(0xc8201aec60, 0xc8200b2af0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/process.go:40 +0xb0
created by github.com/omniscale/imposm3/parser/pbf.(*parser).Parse
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/process.go:49 +0x95

goroutine 27 [chan send]:
github.com/omniscale/imposm3/parser/pbf.(*parser).parseBlock(0xc8200b2af0, 0x7fff5fbfe318, 0x20, 0x5cd968a, 0x16a5e)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/process.go:95 +0x53d
github.com/omniscale/imposm3/parser/pbf.(*parser).Parse.func1(0xc8201aec60, 0xc8200b2af0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/process.go:40 +0xb0
created by github.com/omniscale/imposm3/parser/pbf.(*parser).Parse
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/process.go:49 +0x95

goroutine 28 [runnable]:
compress/flate.(*decompressor).moreBits(0xc820880000, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/compress/flate/inflate.go:718
compress/flate.(*decompressor).huffSym(0xc820880000, 0xc820880030, 0xac, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/compress/flate/inflate.go:741 +0x5b
compress/flate.(*decompressor).huffmanBlock(0xc820880000)
	/usr/local/Cellar/go/1.6.2/libexec/src/compress/flate/inflate.go:485 +0x46
compress/flate.(*decompressor).nextBlock(0xc820880000)
	/usr/local/Cellar/go/1.6.2/libexec/src/compress/flate/inflate.go:338 +0x3a8
compress/flate.(*decompressor).Read(0xc820880000, 0xc820390000, 0xfcbf, 0xfcbf, 0x8000, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/compress/flate/inflate.go:355 +0x1ae
compress/zlib.(*reader).Read(0xc820014690, 0xc820390000, 0xfcbf, 0xfcbf, 0x8000, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/compress/zlib/reader.go:95 +0xe6
io.ReadAtLeast(0x5209fd8, 0xc820014690, 0xc820378000, 0x27cbf, 0x27cbf, 0x27cbf, 0x18000, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/io/io.go:297 +0xe6
io.ReadFull(0x5209fd8, 0xc820014690, 0xc820378000, 0x27cbf, 0x27cbf, 0x27cbf, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/io/io.go:315 +0x62
github.com/omniscale/imposm3/parser/pbf.readBlobData(0x7fff5fbfe318, 0x20, 0x5d06eb3, 0xc8000168e4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:65 +0x889
github.com/omniscale/imposm3/parser/pbf.readPrimitiveBlock(0x7fff5fbfe318, 0x20, 0x5d06eb3, 0x168e4, 0x9a)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:74 +0x60
github.com/omniscale/imposm3/parser/pbf.(*parser).parseBlock(0xc8200b2af0, 0x7fff5fbfe318, 0x20, 0x5d06eb3, 0x168e4)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/process.go:86 +0x58
github.com/omniscale/imposm3/parser/pbf.(*parser).Parse.func1(0xc8201aec60, 0xc8200b2af0)
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/process.go:40 +0xb0
created by github.com/omniscale/imposm3/parser/pbf.(*parser).Parse
	/Users/robin/src/go/src/github.com/omniscale/imposm3/parser/pbf/process.go:49 +0x95
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x401045b]

runtime stack:
runtime.throw(0x46f8d40, 0x2a)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x492be80)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).freeSpan.func1()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:726 +0x186
runtime.systemstack(0x70000f08dc10)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).freeSpan(0x492be80, 0x57481f0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mheap.go:727 +0x44
runtime.(*mcentral).freeSpan(0x492e420, 0x57481f0, 0x2, 0xc820c00000, 0xc820c01000, 0x50800003100, 0x57000000000)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mcentral.go:199 +0x28b
runtime.(*mspan).sweep(0x57481f0, 0x4a300000400, 0x200000201)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mgcsweep.go:319 +0x613
runtime.sweepone(0x4035bd2)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mgcsweep.go:112 +0x23e
runtime.gosweepone.func1()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/mgcsweep.go:124 +0x21
runtime.systemstack(0xc820486640)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/proc.go:1051
```

**Comment by robinhouston** [comment]
Upgrading to go 1.7.3 (and rebuilding imposm3) seems to resolve this.
