### ISSUE TITLE
Unable to import planet-190520.osm.pbf

### ISSUE THREAD

**Issue by giggls** [omniscale/imposm3#196]
## Context

Trying to import planet-190520.osm.pbf crashes imposm

## Expected Behavior
Import should work

## Actual Behavior

```
[2019-05-23T20:50:55+02:00] 0:49:00 [progress]  49m0s C: 3617000/s (5207832003) N:   85800/s (123592261) W:  376700/s (573016000) R:      0/s (0)
panic: runtime error: makeslice: len out of range

goroutine 30 [running]:
github.com/omniscale/imposm3/parser/pbf.(*pbf).nextBlobHeader(0xc42018d830, 0xb46adbee8)
        /home/geg/go/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:207 +0x87
github.com/omniscale/imposm3/parser/pbf.(*pbf).nextBlock(0xc42018d830, 0xc42005cfa0, 0x37028, 0xc429b97380)
        /home/geg/go/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:165 +0x2f
github.com/omniscale/imposm3/parser/pbf.(*pbf).BlockPositions.func1(0xc42018d830, 0xc4201922b8)
        /home/geg/go/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:178 +0x88
created by github.com/omniscale/imposm3/parser/pbf.(*pbf).BlockPositions
        /home/geg/go/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:176 +0x92
```

## Steps to Reproduce
Try to import planet-190520.osm.pbf  using the settings from
https://github.com/giggls/osmpoidb

**Comment by olt** [comment]
What version are you running? lowlevel.go is now in go-osm (or vendor/) and in previous versions line 207 contained only a log statement. But maybe the error is wrong.

Can you rule out that you ran out of memory and that the planet file is not corrupted (MD5)?

**Comment by giggls** [comment]
I just did a database reimport and using my old binary.
Thus this is still 37464958ac6a88ddeb0cc8eb7da7ed59dd4017da
Maybe this weeks planet is just broken. Using the one from last week worked fine.
