### ISSUE TITLE
Killed after reading nodes

### ISSUE THREAD

**Issue by pnorman** [omniscale/imposm3#90]
With imposm3-0.1dev-20160128-bb3d003-linux-x86-64 from the website I get this error when importing planet-160208.osm.pbf

```
[Feb 13 01:16:52] [INFO] [2h37m0s] C:  630000/s (3210564187) N:   16600/s (84831038) W:   64400/s (278656000) R:      0/s (0)

[signal 0x7 code=0x2 addr=0x7fa320de0ff0 pc=0x7fa3700211fe]

runtime stack:
runtime.throw(0xa63800, 0x2a)
        /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 20 [syscall, locked to thread]:
runtime.cgocall(0x407a56, 0xc820040c50, 0x0)
        /usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc820040c20 sp=0xc820040bf0
github.com/jmhodges/levigo._Cfunc_leveldb_write(0x22dec20, 0x22dc650, 0x7fa2680008c0, 0xc84e606050)
        github.com/jmhodges/levigo/_obj/_cgo_gotypes.go:807 +0x35 fp=0xc820040c50 sp=0xc820040c20
github.com/jmhodges/levigo.(*DB).Write(0xc8201660a8, 0xc8201660b0, 0xc84e606048, 0x0, 0x0)
        /home/os/imposm/src/github.com/omniscale/imposm3/Godeps/_workspace/src/github.com/jmhodges/levigo/db.go:217 +0x73 fp=0xc820040cb8 sp=0xc820040c50
github.com/omniscale/imposm3/cache.(*WaysCache).PutWays(0xc82015c720, 0xc836424000, 0x1f40, 0x1f40, 0x0, 0x0)
        /home/os/imposm/src/github.com/omniscale/imposm3/cache/ways.go:50 +0x1c4 fp=0xc820040e50 sp=0xc820040cb8
github.com/omniscale/imposm3/reader.ReadPbf.func3(0xc8200170c0, 0xc82015a4e0, 0xc8201548b0, 0xc820154870, 0xc820168000, 0xc820154550, 0xc8201548c0)
        /home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:130 +0x41f fp=0xc820040f78 sp=0xc820040e50
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820040f80 sp=0xc820040f78
created by github.com/omniscale/imposm3/reader.ReadPbf
        /home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:138 +0x6cc

goroutine 1 [semacquire, 157 minutes]:
sync.runtime_Semacquire(0xc82015e44c)
        /usr/local/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc82015e440)
        /usr/local/go/src/sync/waitgroup.go:126 +0xb4
github.com/omniscale/imposm3/parser/pbf.(*parser).Parse(0xc82015e410)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:51 +0xc9
github.com/omniscale/imposm3/reader.ReadPbf(0xc820168000, 0xc820154550, 0xc8200170c0, 0xc82015c7e0, 0x0)
        /home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:241 +0x971
github.com/omniscale/imposm3/import_.Import()
        /home/os/imposm/src/github.com/omniscale/imposm3/import_/import.go:120 +0xa87
github.com/omniscale/imposm3/cmd.Main(0xaab9b8)
        /home/os/imposm/src/github.com/omniscale/imposm3/cmd/main.go:46 +0x2d2
main.main()
        /home/os/imposm/src/github.com/omniscale/imposm3/imposm3.go:8 +0x23

goroutine 17 [syscall, 157 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [runnable]:
time.nextStdChunk(0x9c3e93, 0xc, 0x3, 0x2, 0xd, 0x2b, 0xc)
        /usr/local/go/src/time/format.go:120
time.Time.AppendFormat(0xece507b1b, 0x18455965, 0xe60100, 0xc820053868, 0x3, 0x40, 0x9c3e93, 0xc, 0x0, 0x0, ...)
        /usr/local/go/src/time/format.go:449 +0x11d
time.Time.Format(0xece507b1b, 0x18455965, 0xe60100, 0x9c3e90, 0xf, 0x0, 0x0)
        /usr/local/go/src/time/format.go:430 +0xf2
github.com/omniscale/imposm3/logging.(*LogBroker).printPrefix(0xe600a0)
        /home/os/imposm/src/github.com/omniscale/imposm3/logging/logger.go:177 +0x84
github.com/omniscale/imposm3/logging.(*LogBroker).printRecord(0xe600a0, 0x1, 0x9bc940, 0x6, 0xc82c828120, 0x59)
        /home/os/imposm/src/github.com/omniscale/imposm3/logging/logger.go:200 +0x110
github.com/omniscale/imposm3/logging.(*LogBroker).loop(0xe600a0)
        /home/os/imposm/src/github.com/omniscale/imposm3/logging/logger.go:145 +0x264
created by github.com/omniscale/imposm3/logging.init.1
        /home/os/imposm/src/github.com/omniscale/imposm3/logging/logger.go:240 +0x17a

goroutine 7 [chan receive, 157 minutes]:
database/sql.(*DB).connectionOpener(0xc82000b680)
        /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 18 [select]:
github.com/omniscale/imposm3/stats.(*Statistics).loop(0xc820154550)
        /home/os/imposm/src/github.com/omniscale/imposm3/stats/stats.go:109 +0x1bd
created by github.com/omniscale/imposm3/stats.NewStatsReporter
        /home/os/imposm/src/github.com/omniscale/imposm3/stats/stats.go:88 +0xa6

goroutine 19 [runnable, locked to thread]:                                                                                                              [85/411]
github.com/jmhodges/levigo._Cfunc_leveldb_writebatch_put(0x7fa300002f20, 0xc84aa14030, 0x8, 0xc829a98000, 0x25)
        github.com/jmhodges/levigo/_obj/_cgo_gotypes.go:871 +0x35
github.com/jmhodges/levigo.(*WriteBatch).Put(0xc843f9e098, 0xc84aa14030, 0x8, 0x8, 0xc829a98000, 0x25, 0x30)
        /home/os/imposm/src/github.com/omniscale/imposm3/Godeps/_workspace/src/github.com/jmhodges/levigo/batch.go:51 +0x6e
github.com/omniscale/imposm3/cache.(*WaysCache).PutWays(0xc82015c720, 0xc859726000, 0x1f40, 0x1f40, 0x0, 0x0)
        /home/os/imposm/src/github.com/omniscale/imposm3/cache/ways.go:48 +0x440
github.com/omniscale/imposm3/reader.ReadPbf.func3(0xc8200170c0, 0xc82015a4e0, 0xc8201548b0, 0xc820154870, 0xc820168000, 0xc820154550, 0xc8201548c0)
        /home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:130 +0x41f
created by github.com/omniscale/imposm3/reader.ReadPbf
        /home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:138 +0x6cc

goroutine 21 [chan receive, 157 minutes]:
github.com/omniscale/imposm3/reader.ReadPbf.func4(0xc8200170c0, 0xc82015a5a0, 0xc820154870, 0xc820168000, 0xc820154550, 0xc8201548c0)
        /home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:147 +0xd9
created by github.com/omniscale/imposm3/reader.ReadPbf
        /home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:176 +0x780

goroutine 22 [chan receive, 157 minutes]:
github.com/omniscale/imposm3/reader.ReadPbf.func4(0xc8200170c0, 0xc82015a5a0, 0xc820154870, 0xc820168000, 0xc820154550, 0xc8201548c0)
        /home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:147 +0xd9
created by github.com/omniscale/imposm3/reader.ReadPbf
        /home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:176 +0x780

goroutine 23 [chan receive, 72 minutes]:
github.com/omniscale/imposm3/reader.ReadPbf.func5(0xc82015a420, 0xc8201548a0, 0xc820154870, 0x0, 0xc820168000, 0xc820154550, 0xc8201548c0)
        /home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:186 +0xb3
created by github.com/omniscale/imposm3/reader.ReadPbf
        /home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:206 +0x85b

goroutine 24 [chan receive, 72 minutes]:
github.com/omniscale/imposm3/reader.ReadPbf.func5(0xc82015a420, 0xc8201548a0, 0xc820154870, 0x0, 0xc820168000, 0xc820154550, 0xc8201548c0)
        /home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:186 +0xb3
created by github.com/omniscale/imposm3/reader.ReadPbf
        /home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:206 +0x85b

goroutine 25 [chan receive, 72 minutes]:
github.com/omniscale/imposm3/reader.ReadPbf.func6(0xc8200170c0, 0xc82015a360, 0xc8201548a0, 0xc820154870, 0x0, 0xc820168000, 0xc820154550, 0xc8201548c0)
        /home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:216 +0xc6
created by github.com/omniscale/imposm3/reader.ReadPbf
        /home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:238 +0x943

goroutine 26 [chan receive, 72 minutes]:
github.com/omniscale/imposm3/reader.ReadPbf.func6(0xc8200170c0, 0xc82015a360, 0xc8201548a0, 0xc820154870, 0x0, 0xc820168000, 0xc820154550, 0xc8201548c0)
        /home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:216 +0xc6
created by github.com/omniscale/imposm3/reader.ReadPbf
        /home/os/imposm/src/github.com/omniscale/imposm3/reader/reader.go:238 +0x943

goroutine 27 [chan send]:
github.com/omniscale/imposm3/parser/pbf.(*Pbf).BlockPositions.func1(0xc82015c7e0, 0xc820166128)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:173 +0x191
created by github.com/omniscale/imposm3/parser/pbf.(*Pbf).BlockPositions
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/lowlevel.go:175 +0x96

goroutine 28 [chan send]:                                                                                                                               [31/411]
github.com/omniscale/imposm3/parser/pbf.(*parser).parseBlock(0xc82015e410, 0x7ffd0a3fe75c, 0x18, 0x75148053a, 0x33f993)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:112 +0x524
github.com/omniscale/imposm3/parser/pbf.(*parser).Parse.func1(0xc82015a660, 0xc82015e410)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:40 +0xb0
created by github.com/omniscale/imposm3/parser/pbf.(*parser).Parse
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:49 +0x95

goroutine 29 [chan send]:
github.com/omniscale/imposm3/parser/pbf.(*parser).parseBlock(0xc82015e410, 0x7ffd0a3fe75c, 0x18, 0x750e59aaa, 0x32f9ca)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:112 +0x524
github.com/omniscale/imposm3/parser/pbf.(*parser).Parse.func1(0xc82015a660, 0xc82015e410)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:40 +0xb0
created by github.com/omniscale/imposm3/parser/pbf.(*parser).Parse
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:49 +0x95

goroutine 30 [chan send]:
github.com/omniscale/imposm3/parser/pbf.(*parser).parseBlock(0xc82015e410, 0x7ffd0a3fe75c, 0x18, 0x7517bfedf, 0x3228b6)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:112 +0x524
github.com/omniscale/imposm3/parser/pbf.(*parser).Parse.func1(0xc82015a660, 0xc82015e410)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:40 +0xb0
created by github.com/omniscale/imposm3/parser/pbf.(*parser).Parse
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:49 +0x95

goroutine 31 [runnable]:
github.com/omniscale/imposm3/parser/pbf.parseTags(0xc845a08000, 0x8f32, 0x8f32, 0xc83f1b7930, 0x1, 0x2, 0xc83f1b7940, 0x1, 0x2, 0xc820ad30e0)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/pbf.go:90 +0x153
github.com/omniscale/imposm3/parser/pbf.readWays(0xc84fa10000, 0x1f40, 0x2400, 0xc84708f440, 0xc845a08000, 0x8f32, 0x8f32, 0x0, 0x0, 0x0)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/pbf.go:151 +0x17e
github.com/omniscale/imposm3/parser/pbf.(*parser).parseBlock(0xc82015e410, 0x7ffd0a3fe75c, 0x18, 0x751ae27a7, 0x2f465b)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:107 +0x466
github.com/omniscale/imposm3/parser/pbf.(*parser).Parse.func1(0xc82015a660, 0xc82015e410)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:40 +0xb0
created by github.com/omniscale/imposm3/parser/pbf.(*parser).Parse
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:49 +0x95

goroutine 32 [chan send]:
github.com/omniscale/imposm3/parser/pbf.(*parser).parseBlock(0xc82015e410, 0x7ffd0a3fe75c, 0x18, 0x751dd6e14, 0x2f2c2a)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:112 +0x524
github.com/omniscale/imposm3/parser/pbf.(*parser).Parse.func1(0xc82015a660, 0xc82015e410)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:40 +0xb0
created by github.com/omniscale/imposm3/parser/pbf.(*parser).Parse
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:49 +0x95

goroutine 33 [chan send]:
github.com/omniscale/imposm3/parser/pbf.(*parser).parseBlock(0xc82015e410, 0x7ffd0a3fe75c, 0x18, 0x7520c9a50, 0x304c8b)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:112 +0x524
github.com/omniscale/imposm3/parser/pbf.(*parser).Parse.func1(0xc82015a660, 0xc82015e410)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:40 +0xb0
created by github.com/omniscale/imposm3/parser/pbf.(*parser).Parse
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:49 +0x95

goroutine 34 [chan send]:
github.com/omniscale/imposm3/parser/pbf.(*parser).parseBlock(0xc82015e410, 0x7ffd0a3fe75c, 0x18, 0x7527099a8, 0x350ea2)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:112 +0x524
github.com/omniscale/imposm3/parser/pbf.(*parser).Parse.func1(0xc82015a660, 0xc82015e410)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:40 +0xb0
created by github.com/omniscale/imposm3/parser/pbf.(*parser).Parse
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:49 +0x95

goroutine 35 [chan send]:
github.com/omniscale/imposm3/parser/pbf.(*parser).parseBlock(0xc82015e410, 0x7ffd0a3fe75c, 0x18, 0x7523ce6ed, 0x33b2a9)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:112 +0x524
github.com/omniscale/imposm3/parser/pbf.(*parser).Parse.func1(0xc82015a660, 0xc82015e410)
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:40 +0xb0
created by github.com/omniscale/imposm3/parser/pbf.(*parser).Parse
        /home/os/imposm/src/github.com/omniscale/imposm3/parser/pbf/process.go:49 +0x95

```

Command line was ``imposm3-0.1dev-20160128-bb3d003-linux-x86-64/imposm3 import -mapping CartoDB-basemaps/imposm3_mapping.json -connection='postgis://?prefix=NONE' -read ../planet-160208.osm.pbf -write -deployproduction -overwritecache``

3210564187 matches closely with the total number of nodes

**Comment by pnorman** [comment]
Might be related to space limits on the drive being used, but a segfault still seems like an error

**Comment by olt** [comment]
It does crash if it runs out of free space. This is a "feature" of LevelDB that Imposm can't work around. I've added a note to the documentation: 4ad6843
